#spring.datasource.driver-class-name=com.mysql.jdbc.Driver


server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: "password"
    url: jdbc:mysql://localhost:3306/consultdb
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nobodycares2997@gmail.com
    password: jkspzocpleioqwwh
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
